id = "html-snippets"
name = "HTML Snippets"
version = "0.1.0"
schema_version = 1
description = "Essential HTML snippets for faster development"
repository = "https://github.com/seekode/zed-html-snippets"
authors = ["seekode <nicolas@seekode.dev>"]
themes = []
icon_themes = []
languages = []
snippets = "./snippets/html.json"
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
