id = "javascript-snippets"
name = "JavaScript Snippets"
version = "0.1.0"
schema_version = 1
description = "Essential JavaScript snippets for faster development"
repository = "https://github.com/seekode/zed-js-snippets"
authors = ["seekode <nicolas@seekode.dev>"]
themes = []
icon_themes = []
languages = []
snippets = "./snippets/javascript.json"
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
